swagger: '2.0'
info:
  title: Test CRUD
  version: "0.1"
  description: Test CRUD
consumes:
  - application/json
produces:
  - application/json
paths:
  /user/{user_id}:
    get:
      tags: [users]
      operationId: app.get_user
      summary: Get a single user
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return user
          schema:
            $ref: '#/definitions/user_obj'
        404:
          description: user does not exist
    put:
      tags: [users]
      operationId: app.put_user
      summary: Create or update a user
      parameters:
        - $ref: '#/parameters/user_id'
        - name: user_obj
          in: body
          schema:
            $ref: '#/definitions/user_obj'
      responses:
        200:
          description: user updated
        201:
          description: New user created
        422:
          description: User not created
    delete:
      tags: [users]
      operationId: app.delete_user
      summary: Remove a user
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        204:
          description: user was deleted
        404:
          description: user does not exist


parameters:
  user_id:
    name: user_id
    description: user's Unique identifier
    in: path
    type: integer
    required: true

definitions:
  user_obj:
    type: object
    